General refactoring and consolidation
uphold/rest-api-examples pull request #5
Opened 2020-11-17 17:13 UTC by waldyrious

This PR implements various cleanup changes to consolidate and clean up the repository contents and structure after the initial seeding in #1, #2, #3 and #4. Namely, the following changes have been performed:

- Clean up git tracking of package lock files;
- Refactor and standardize syntax and code formatting across all files, including harmonization of the syntax of Axios requests, and simplification of the transaction sample code;
- Trim down samples' dependencies (removing over a hundred dependent packages);
- Add main README file;
- Improve documentation in sample projects' names, descriptions, and READMEs;
- Reorganize and rename directories to provide a clearer and more self-consistent naming scheme for the samples, and facilitate navigation.

2020-11-18 08:42 UTC, inginheiiro approved these changes
LGTM

2020-12-06 10:26 UTC, nunojsferreira requested changes

2020-12-09 14:01 UTC, inginheiiro requested changes
fixed issues with **bearer** and names

2020-12-14 14:52 UTC, nunojsferreira approved these changes

2020-12-14 14:59 UTC, merged